// Dummy data matching Flutter app's contract_service.dart

export const users = {
  'USER-001': {
    id: 'USER-001',
    name: 'SpongeBob SquarePants',
    ic: '901212-10-5599',
    avatar: '/images/mykad_sponge.png',
    email: 'spongebob@bikinibottom.sea',
    phone: '+60 12-345 6789',
  },
  'USER-002': {
    id: 'USER-002',
    name: 'Ultraman Taro',
    ic: '850505-14-3344',
    avatar: '/images/mykad_Ultraman.png',
    email: 'ultraman@m78.nebula',
    phone: '+60 98-765 4321',
  },
};

export const contractStatuses = {
  ONGOING: 'Ongoing',
  PENDING: 'Pending',
  COMPLETED: 'Completed',
  BREACHED: 'Breached',
  DECLINED: 'Declined',
};

export const statusColors = {
  Ongoing: 'bg-status-ongoing',
  Pending: 'bg-status-pending',
  Completed: 'bg-status-completed',
  Breached: 'bg-status-breached',
  Declined: 'bg-gray-500',
};

export const statusTextColors = {
  Ongoing: 'text-status-ongoing',
  Pending: 'text-status-pending',
  Completed: 'text-status-completed',
  Breached: 'text-status-breached',
  Declined: 'text-gray-600',
};

export const initialContracts = [
  // SpongeBob's contracts (USER-001)
  {
    id: 'CNT-001',
    name: 'Rental Camera',
    topic: 'Photography Equipment',
    status: 'Ongoing',
    userId: 'USER-001',
    accepteeId: 'USER-002',
    signatureDate: new Date(2025, 8, 15),
    dueDate: new Date(2025, 11, 20),
    templateType: 'ITEM_BORROW',
    formData: null,
    creatorSignature: null,
    accepteeSignature: null,
  },
  {
    id: 'CNT-002',
    name: 'Renovation Deposit',
    topic: 'Home Improvement',
    status: 'Breached',
    userId: 'USER-001',
    accepteeId: 'USER-002',
    signatureDate: new Date(2025, 7, 1),
    dueDate: new Date(2025, 11, 31),
    templateType: 'SALE_DEPOSIT',
    formData: null,
    creatorSignature: null,
    accepteeSignature: null,
  },
  {
    id: 'CNT-003',
    name: 'Freelance Design',
    topic: 'Creative Services',
    status: 'Completed',
    userId: 'USER-001',
    accepteeId: 'USER-002',
    signatureDate: new Date(2025, 6, 10),
    dueDate: new Date(2025, 11, 15),
    templateType: 'FREELANCE_JOB',
    formData: null,
    creatorSignature: null,
    accepteeSignature: null,
  },
  {
    id: 'CNT-004',
    name: 'Equipment Loan',
    topic: 'Business Equipment',
    status: 'Ongoing',
    userId: 'USER-001',
    accepteeId: 'USER-002',
    signatureDate: new Date(2025, 8, 5),
    dueDate: new Date(2026, 0, 5),
    templateType: 'ITEM_BORROW',
    formData: null,
    creatorSignature: null,
    accepteeSignature: null,
  },
  {
    id: 'CNT-005',
    name: 'Service Agreement',
    topic: 'Professional Services',
    status: 'Ongoing',
    userId: 'USER-001',
    accepteeId: 'USER-002',
    signatureDate: new Date(2025, 9, 1),
    dueDate: new Date(2025, 11, 25),
    templateType: 'FREELANCE_JOB',
    formData: null,
    creatorSignature: null,
    accepteeSignature: null,
  },
  {
    id: 'CNT-006',
    name: 'Personal Loan',
    topic: 'Financial Loan',
    status: 'Pending',
    userId: 'USER-001',
    accepteeId: 'USER-002',
    signatureDate: new Date(2025, 9, 5),
    dueDate: new Date(2025, 11, 30),
    templateType: 'FRIENDLY_LOAN',
    formData: {
      amount: 5000,
      purpose: 'Personal expenses',
      date: '2025-12-30',
    },
    creatorSignature: null,
    accepteeSignature: null,
  },
  // Ultraman's contracts (USER-002)
  {
    id: 'CNT-101',
    name: 'Wedding Photography',
    topic: 'Event Photography Services',
    status: 'Ongoing',
    userId: 'USER-002',
    accepteeId: 'USER-001',
    signatureDate: new Date(2025, 8, 20),
    dueDate: new Date(2025, 11, 18),
    templateType: 'FREELANCE_JOB',
    formData: null,
    creatorSignature: null,
    accepteeSignature: null,
  },
  {
    id: 'CNT-102',
    name: 'Car Rental Payment',
    topic: 'Vehicle Rental Agreement',
    status: 'Ongoing',
    userId: 'USER-002',
    accepteeId: 'USER-001',
    signatureDate: new Date(2025, 8, 10),
    dueDate: new Date(2026, 0, 10),
    templateType: 'VEHICLE_USE',
    formData: null,
    creatorSignature: null,
    accepteeSignature: null,
  },
  {
    id: 'CNT-103',
    name: 'House Rental Deposit',
    topic: 'Property Rental',
    status: 'Pending',
    userId: 'USER-002',
    accepteeId: 'USER-001',
    signatureDate: new Date(2025, 9, 8),
    dueDate: new Date(2026, 0, 8),
    templateType: 'SALE_DEPOSIT',
    formData: {
      item: 'House Rental',
      deposit: 3000,
      price: 1500,
    },
    creatorSignature: null,
    accepteeSignature: null,
  },
  {
    id: 'CNT-104',
    name: 'Interior Design Work',
    topic: 'Design Services',
    status: 'Ongoing',
    userId: 'USER-002',
    accepteeId: 'USER-001',
    signatureDate: new Date(2025, 7, 15),
    dueDate: new Date(2025, 11, 28),
    templateType: 'FREELANCE_JOB',
    formData: null,
    creatorSignature: null,
    accepteeSignature: null,
  },
  {
    id: 'CNT-105',
    name: 'Catering Service',
    topic: 'Event Catering',
    status: 'Completed',
    userId: 'USER-002',
    accepteeId: 'USER-001',
    signatureDate: new Date(2025, 5, 20),
    dueDate: new Date(2025, 11, 10),
    templateType: 'FREELANCE_JOB',
    formData: null,
    creatorSignature: null,
    accepteeSignature: null,
  },
];

export const contractCategories = [
  {
    id: 'items_assets',
    name: 'Items & Assets',
    description: 'Borrowing physical items or vehicles',
    icon: 'Package',
    color: 'from-blue-500 to-cyan-500',
    templates: [
      {
        id: 'VEHICLE_USE',
        name: 'Vehicle Borrowing',
        description: 'Lend or borrow a vehicle temporarily',
        icon: 'Car',
        fields: ['model', 'plate', 'startDate', 'endDate', 'fuel'],
      },
      {
        id: 'ITEM_BORROW',
        name: 'Item Borrowing',
        description: 'Lend or borrow personal items',
        icon: 'Package',
        fields: ['item', 'condition', 'returnDate', 'value'],
      },
    ],
  },
  {
    id: 'money_finance',
    name: 'Money & Finance',
    description: 'Loans and shared expenses',
    icon: 'Banknote',
    color: 'from-green-500 to-emerald-500',
    templates: [
      {
        id: 'BILL_SPLIT',
        name: 'Bill Split',
        description: 'Split shared expenses with others',
        icon: 'Receipt',
        fields: ['description', 'total', 'share', 'date'],
      },
      {
        id: 'FRIENDLY_LOAN',
        name: 'Friendly Loan',
        description: 'Personal loan between friends/family',
        icon: 'Banknote',
        fields: ['amount', 'purpose', 'date'],
      },
    ],
  },
  {
    id: 'service_gig',
    name: 'Service & Gig Work',
    description: 'Freelance jobs and sales',
    icon: 'Briefcase',
    color: 'from-purple-500 to-pink-500',
    templates: [
      {
        id: 'FREELANCE_JOB',
        name: 'Freelance Job',
        description: 'Service or gig work agreement',
        icon: 'Briefcase',
        fields: ['task', 'deadline', 'price', 'deposit'],
      },
      {
        id: 'SALE_DEPOSIT',
        name: 'Sales & Deposit',
        description: 'Sale with deposit agreement',
        icon: 'ShoppingBag',
        fields: ['item', 'price', 'deposit', 'dueDate'],
      },
    ],
  },
];

// Flat list of all templates for backward compatibility
export const contractTemplates = contractCategories.flatMap(cat => cat.templates);
